server:
  port: 20021
  tomcat:
    connection-timeout: 60000
  servlet:
    context-path: /saffron-crawler
spring:
  application:
    name: crawler-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:3306/saffron_chaos?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      max-lifetime: 18000
      pool-name: SaffronCP
  mail:
    password: dxutmoiieygubfcd
    username: 850338501@qq.com
    host: smtp.qq.com
    port: 465
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          starttls:
            enable: true
            required: true
#  rabbitmq:
#    host: ${MYSQL_HOST:rabbitmq}
#    port: 5672
#    username: guest
#    password: guest
#    virtual-host: /
#    listener:
#      direct:
#        acknowledge-mode: auto
#  minio:
#    bucket: saffron
#    endpoint: http://${MINIO_HOST:minio}:9000
#    accessKey: saffron
#    secretKey: saffron123
#  data:
#    redis:
#      host: ${REDIS_HOST:redis}
#      database: 0
#      port: 6379
#      timeout: 10s
#  elasticsearch:
#    uris: http://${ES_HOST:es}:9200
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  xxl:
    url: http://${XXL_HOST:xxl-admin}:10000/xxl-job-admin
    access-token: default_token
    app-name: saffron-crawler
    port: 10001
    log-retention-days: 30
saffron:
  enableJob: true
  enableListener: true
logging:
  level:
    root: error
    com.w.saffron: info
